// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: figure_cards.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFigureCard = `-- name: CreateFigureCard :one
INSERT INTO
	figure_cards (id, show, player_id, game_id, type, blocked, soft_blocked)
VALUES
	($1, $2, $3, $4, $5, $6 ,$7)
RETURNING id, show, difficulty, player_id, game_id, type, blocked, soft_blocked
`

type CreateFigureCardParams struct {
	ID          uuid.UUID
	Show        bool
	PlayerID    uuid.UUID
	GameID      uuid.UUID
	Type        string
	Blocked     bool
	SoftBlocked bool
}

func (q *Queries) CreateFigureCard(ctx context.Context, arg CreateFigureCardParams) (FigureCard, error) {
	row := q.db.QueryRowContext(ctx, createFigureCard,
		arg.ID,
		arg.Show,
		arg.PlayerID,
		arg.GameID,
		arg.Type,
		arg.Blocked,
		arg.SoftBlocked,
	)
	var i FigureCard
	err := row.Scan(
		&i.ID,
		&i.Show,
		&i.Difficulty,
		&i.PlayerID,
		&i.GameID,
		&i.Type,
		&i.Blocked,
		&i.SoftBlocked,
	)
	return i, err
}
