// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Game struct {
	ID         uuid.UUID
	Name       string
	MaxPlayers int32
	MinPlayers int32
	IsPrivate  bool
	Password   sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type GameState struct {
	ID              uuid.UUID
	State           string
	GameID          uuid.NullUUID
	CurrentPlayerID uuid.NullUUID
	ForbiddenColor  sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Player struct {
	ID          uuid.UUID
	Name        string
	Turn        sql.NullString
	GameID      uuid.NullUUID
	GameStateID uuid.NullUUID
	Host        bool
	Winner      bool
	CreatedAt   time.Time
	UpdateAt    time.Time
}
